### PR TITLE
Microsoft GitHub policy service visual studio code

### PR DESCRIPTION
**Pull request by Neiland85**

### CODE REVIEW

**Comment by Viktoryurist1** [comment]
> copy

**Review by Neiland85 — COMMENTED** [review]
uplad & installng LÉAME.md

**Review by Neiland85 — COMMENTED** [review]
Microsoft GitHub policy service visual studio code #66

**Review by Neiland85 — COMMENTED** [review]
README.md
Microsoft GitHub policy service visual studio code #66

**Review by Neiland85 — COMMENTED** [review]
Microsoft GitHub policy service visual studio code #66

**Pull request closed without merging**
